# Apache Superset Dev Container -- Docker Compose

# WARNING -- Verify .devcontainer/superset.env exists before building
# INFO    -- Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
#            (Adding the "ports" property to this file will not forward from a Codespace.)
# INFO    -- Volume env variables (like EXPORTSPATH, CERTSPATH) are loaded from .devcontainer/.env

version: "3.8"

services:
  app:
    container_name: app
    build:
      context: ..
      args:
        USER_NAME: ${USER}
        USER_UID: ${UID}
        USER_GID: ${GID}
    env_file: superset.env
    init: true
    volumes:
      - ..:/workspace
      - $EXPORTSPATH:/app/exports:cached
      - $CERTSPATH:/app/certs:cached
      - $TLSPATH:/app/tls:cached # only mount when testing SSL
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - network
    depends_on:
      - db
    mem_limit: 16gb
    shm_size: 4gb

  db:
    image: mysql:8
    container_name: superset-db
    restart: unless-stopped
    volumes:
      - $MYSQL_INI:/docker-entrypoint-initdb.d/
    env_file: superset.env
    networks:
      - network
    ports:
      - 127.0.0.1:3307:3306

  redis:
    image: redis:7
    container_name: superset-redis
    restart: unless-stopped
    env_file: superset.env
    networks:
      - network
    ports:
      - 127.0.0.1:6379:6379

  superset-worker:
    container_name: worker
    command: [ "celery", "--app=superset.tasks.celery_app:app", "worker", "--pool=prefork", "-O", "fair", "-c", "4" ]
    env_file: superset.env
    restart: unless-stopped
    networks:
      - network
    depends_on:
      - db
      - redis
    volumes:
      - $CERTSPATH:/app/certs:cached
      - $YAHOOPATH:/app/yahoo:ro # set yahoo certs to readonly
      - ../config:/app/pythonpath:cached
      - ./volumes/logs:/app/logs:rw
    healthcheck:
      test: [ "CMD-SHELL", "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME" ]
    # Bump memory limit if processing selenium / thumbnails on superset-worker
    mem_limit: 14gb
    shm_size: 4gb
    mem_reservation: 512m

  superset-worker-beat:
    container_name: beat
    command: [ "celery", "--app=superset.tasks.celery_app:app", "beat", "-s", "/tmp/celerybeat-schedule" ]
    env_file: superset.env
    restart: unless-stopped
    networks:
      - network
    depends_on:
      - db
      - redis
    volumes:
      - $CERTSPATH:/app/certs:cached
      - ../config:/app/pythonpath:cached
    healthcheck:
      disable: true

networks:
  network:
    driver: bridge
